[package]
name = "cairo-xcb"
version = "0.1.0"
authors = ["Dmitry Kurbatov <dk@dimcha.ru>"]

[dependencies]
libc = "0.2"
xcb = { git = "https://github.com/kandeshvari/rust-xcb.git", rev = "05a4716" }
glib = "^0"
cairo-rs = "^0"
cairo-sys-rs = "^0"


[lib]
name = "cairo_xcb"